[".local/bin/rustup-init"]
type = "file"
url = "https://sh.rustup.rs"
executable = true
refreshPeriod = "168h"

[".local/bin/sdkman-init"]
type = "file"
url = "https://get.sdkman.io?rcupdate=false"
executable = true
refreshPeriod = "168h"

[".local/bin/slack-init"]
type = "file"
url = "https://downloads.slack-edge.com/slack-cli/install.sh"
executable = true
refreshPeriod = "168h"

[".local/bin/kerl"]
type = "file"
url = "https://raw.githubusercontent.com/kerl/kerl/master/kerl"
executable = true
refreshPeriod = "168h"

[".local/bin/k0s-init"]
type = "file"
url = "https://get.k0s.sh"
executable = true
refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"

[".local/share/nvim/site/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"

[".zsh/.antidote"]
type = "git-repo"
url = "git@github.com:mattmc3/antidote.git"
refreshPeriod = "168h"
